// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200712141559_SeedDataCategory")]
    partial class SeedDataCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Mobiles",
                            ThumbnailUrl = "images/categories/mobiles.jpg"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Notebooks",
                            ThumbnailUrl = "images/categories/notebooks.jpg"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Tablets",
                            ThumbnailUrl = "images/categories/tablets.jpg"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Computers",
                            ThumbnailUrl = "images/categories/computers.jpg"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Whatches",
                            ThumbnailUrl = "images/categories/whatches.jpg"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Accessories",
                            ThumbnailUrl = "images/categories/accessories.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
